#!/bin/sh

rm -rf _deps
rm -rf CMakeFiles
rm -rf __pycache__
rm CMakeCache.txt

rm -r build
rm -r PyVSparse.egg-info
rm - *.so
rm *.ninja
rm cmake_install.cmake 
rm CMakeCache.txt
rm -rf CMakeFiles
rm -rf classFiles

