name: "Pip" # Source: https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/pip.yml

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Pip
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Pull IVSparse-dev 
      run: git submodule update --init --recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: pytest

  upload_all:
    name: Upload if release
    needs: [build]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1