name: Wheel # https://github.com/pybind/scikit_build_example/blob/master/.github/workflows/wheels.yml

on: 
  workflow_run:
    workflows: [pip]
    types: [completed]
    branches:
      - main

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload_all_on_success:
    name: Upload if tests are succesful
    runs-on: ${{ matrix.os }}
    environment: pypi
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest, macos-14]
        
    permissions:
      id-token: write
      
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
  
      - uses: pypa/cibuildwheel@v2.17
  
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Optional, use if you use setuptools_scm
          submodules: true # Optional, use if you have submodules

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz